name: travel_chain_mvp
description: NFT Market for Travel-based art used as digital keychains..

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

# Auth

# Features
  flutter_map: ^0.14.0
  latlong2: ^0.8.1

# Firebase
#  cloud_firestore_web: ^2.6.7
#  cloud_functions_web: ^4.2.7
#  firebase_analytics_web: ^0.3.0+1
#  firebase_auth_web: ^3.3.7
#  firebase_core_web: ^1.5.4
#  firebase_messaging_web: ^2.2.7
#  firebase_performance_web: ^0.1.0+5
#  firebase_storage_web: ^3.2.7
# State Management
  get_it: ^7.2.0

#Images
  flutter_svg: ^1.0.3

# UI
  responsive_framework: ^0.1.5
  cupertino_icons: ^1.0.2
  flutter_slider_drawer: ^2.1.1
  carousel_slider: ^4.0.0
  curved_navigation_bar: ^1.0.1
  sizer: ^2.0.15
  google_fonts: 2.2.0

# Other
  nil: ^1.1.1
  readmore: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
     - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
